# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160217_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpageauthor',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='blogpageauthor',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
