# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160218_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpageauthor',
            old_name='position',
            new_name='role',
        ),
    ]
